spring.application.name=iam
server.port=8080
server.max-http-request-header-size=65536

spring.datasource.url=jdbc:postgresql://localhost:5432/iam_db
spring.datasource.username=oms_user
spring.datasource.password=new_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Disable Hibernate's automatic schema generation, let Flyway handle it
spring.jpa.hibernate.ddl-auto=validate

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.user=oms_user
spring.flyway.password=new_password

# JWT Configuration
jwt.expiration=86400000
jwt.private-key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCsm6hfuGsvM6WGk96QL3+bs2Z48MVwRLXo79L3zSgFwIGSHXCfwLMxXwoc1ZkaEI/5D+PFT+DNRlsvkxaKQtkO19LWfcxe9gfOwTEwou/m3cMsZp5OnLu0P0a18011fGet5xhBJXMu4s6o9rUNyffQqGqoGjb/h+q742wlJCE6NUOcStTXUKhaOE2QPYzxhDKTCtvPOl60ZhUKN5TaNI4laNblfGQlUpQBkJSqdyhO4z1q0GvfDljsNmxSz+VRSN0CpN2lHZjVCK4X6zcmHrJSZDkp81Yx/UeXFr1KYEbJ7MIeVXDfCfxn33nVEBm7yb40B1rdFiLvGTl7Gvhc2n6FAgMBAAECggEAA2WVBoPg3B04IsBAi4QxHPkjHoFmDNkONBG3RTEJU23f6ZELh2hpsCJunedtiA/y0reOnOQpsxsjEbMcRWPzuJTHu7GlvenH6o3DvnE64CryEPHm7t4dFYkNeJNNWBnTQoI/PcehgNNt72K+oYMBDd8am5AtZTxMAsmRBG7D+jBL7mJ6tY4YGXf6bib8c+KPNC9QSou5LK3cS5XjMPl3J0Lilg2L6A+HMavfpzkFnIde15+2cJ8HBRaCMx2vlm9IvNwsqzPYfIgVh7EIHmF2TSLIngdvt96B9cwBrkriI3h/bMp+iCacePHKdOI3g1E0TQ2DtYqEPv0TbiPic5J4IQKBgQC6MNFR4KxFjxZPEwkA5CAQLIMRXgWZ+m0XNFtpDFqT+TbB9wf5LbNfmCJRx9be2H0dP7tzSWiEdvjPcXSzRmrG8ItPWWZynqj+HrYYN8IFucpVvSnkDmxsBYb9ykBb2YENQMmFG7idATmHkdf5876ilxNexuBCcucOkhbleZLFsQKBgQDtUyILyLVIP8w7fRFFlHwfj+bOpkRRQZ/JDBE8JBZcFWfN4i1ST5bLomrr9aWJKyE69HEGltWM4715GAfPcevp0oiVpHBLSeZ2ZmvSMrcvBOq+7bJwFRM+8+vMO5wqYux7iwXaO9cqRWonUxu6KFijyG/9jatIhCNOzjN5JFt3FQKBgFvN2kfe2dJqXPucTSItWUngSLf1fhmQCt4YKMJBHyA7Dy7QWRQZ3onR/4oHWQEECZy0Yf7UQT6fUssmC/6hR+DTlj0HvaXiaTzzc6G5TGd6VjO0U8Vo/zi7+PWGFfmz4xffy/1fz8VKZ01bMfzCnEqa5ygiM01QTnE2wyderGnhAoGBAOsZ7uFTnFqNcOoBtMmEFg5CRPi0d3szknHdNXmpmkjwn5uykwk2dQEXzeoguDMReeLoYsuPQtBGj93VM2+KwJUrDkmH1AKRm+/w+KELwrKeoVoxKRKlniJAC3iQGN1YkEK27z5JB5cFmuqIBzC8ZUsi9eZtoJ++3ydjWFSK8t0dAoGBALdehd6GTwOg2qWzVQ/e+0A6FXXUGS3SQXqUlbyZFfwaQICwfHuPO/UczPxuB2Y7HNS4uNQI/ZAhF1EvdzvV6xbLpCJXCRZlVu5e5QHEtlHW/5OFB/ckvqCscLbqo5aGOeyuDVevETzuA1O7QpuSZYeGLjWakek1RC11uoFAQ6l+
jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArJuoX7hrLzOlhpPekC9/m7NmePDFcES16O/S980oBcCBkh1wn8CzMV8KHNWZGhCP+Q/jxU/gzUZbL5MWikLZDtfS1n3MXvYHzsExMKLv5t3DLGaeTpy7tD9GtfNNdXxnrecYQSVzLuLOqPa1Dcn30KhqqBo2/4fqu+NsJSQhOjVDnErU11CoWjhNkD2M8YQykwrbzzpetGYVCjeU2jSOJWjW5XxkJVKUAZCUqncoTuM9atBr3w5Y7DZsUs/lUUjdAqTdpR2Y1QiuF+s3Jh6yUmQ5KfNWMf1Hlxa9SmBGyezCHlVw3wn8Z9951RAZu8m+NAda3RYi7xk5exr4XNp+hQIDAQAB

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
