global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "iam"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["iam-service:8080"]
  - job_name: "inventory"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["inventory-service:8082"]
  - job_name: "order"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["order-service:8081"]
  - job_name: "payment"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["payment-service:8083"]
  - job_name: "notification"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:8084"]
