DROP TABLE IF EXISTS inventory CASCADE;

CREATE TABLE inventory (
    product_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(255) NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    available_quantity INTEGER NOT NULL CHECK (available_quantity >= 0),
    reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    version INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed some initial data for testing
INSERT INTO inventory (product_id, product_name, price, available_quantity, reserved_quantity, version, status)
VALUES 
(101, 'MacBook Pro', 1200.00, 50, 0, 0, 'ACTIVE'),
(102, 'iPhone 15', 999.00, 100, 0, 0, 'ACTIVE'),
(103, 'AirPods Pro', 249.00, 200, 0, 0, 'ACTIVE');

-- Ensure sequence matches the seed data
SELECT setval(pg_get_serial_sequence('inventory', 'product_id'), 103);
